"""items-reports

Revision ID: 3da561e7f7c0
Revises: 8a2966b9f7ee
Create Date: 2022-01-16 18:27:11.067205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da561e7f7c0'
down_revision = '8a2966b9f7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_reports',
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('date', sa.Date(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_reports')
    # ### end Alembic commands ###
