"""add column to track times key uses

Revision ID: 8a2966b9f7ee
Revises: 712d42956a47
Create Date: 2021-12-10 14:59:21.787133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a2966b9f7ee'
down_revision = '712d42956a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_keys', sa.Column('times_used', mysql.INTEGER(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_keys', 'times_used')
    # ### end Alembic commands ###
