"""reports

Revision ID: aee4c6c24811
Revises: 8a2966b9f7ee
Create Date: 2022-01-16 20:12:39.816567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee4c6c24811'
down_revision = '8a2966b9f7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('date', sa.Date(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('report_type', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
